Update get-my-kernel-format.yml

diff --git a/.github/workflows/get-my-kernel-format.yml b/.github/workflows/get-my-kernel-format.yml
--- a/.github/workflows/get-my-kernel-format.yml
+++ b/.github/workflows/get-my-kernel-format.yml
@@ -34,12 +34,14 @@ jobs:
           # Ensure magiskboot is executable
           chmod +x magiskboot
 
-          ./magiskboot unpack boot.img
-          #KERNEL_FMT=$(./magiskboot unpack boot.img 2>&1 | grep 'KERNEL_FMT' | cut -f2 -d '[]')
-          #if echo "$KERNEL_FMT" | grep -qi 'gzip'; then
-          #echo "Your kernel format is GZIP (gz)"
-          #elif echo "$KERNEL_FMT" | grep -qi 'lz4'; then
-          #echo "Your kernel format is LZ4 (lz4)"
-          #elif echo "$KERNEL_FMT" | grep -qi 'raw'; then
-          #echo "Your kernel format is raw"
-          #fi
+          KERNEL_FMT=$(./magiskboot unpack boot.img 2>&1 | grep 'KERNEL_FMT' | awk '{print $2}' | tr -d '[]')
+          if echo "$KERNEL_FMT" | grep -qi 'gzip'; then
+          echo "Your kernel format is GZIP (gz)"
+          elif echo "$KERNEL_FMT" | grep -qi 'lz4'; then
+          echo "Your kernel format is LZ4 (lz4)"
+          elif echo "$KERNEL_FMT" | grep -qi 'raw'; then
+          echo "Your kernel format is raw"
+          else
+          echo "error: Unknown kernel format!"
+          exit 1
+          fi
